# docker-compose to run database and api
version: "3"
services:
  api:
    depends_on:
      - postgres
    container_name: back_api
    build: ./back
    ports:
      - "8080:8080"
    networks:
      - default

  postgres:
    image: postgres:11
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - ./back/db/init:/docker-entrypoint-initdb.d
    networks:
      - default

  app:
    depends_on:
      - api
    container_name: react_app
    build: ./front
    ports:
      - "3000:3000"
    networks:
      - default