# docker-compose to run database and api
version: "3"
services:
  app:
    depends_on:
      - postgres
    container_name: back_api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    networks:
      - default

  postgres:
    image: postgres:11
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - default